name: Professional_Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          # دابەزاندنی SDK ی تایبەت بۆ ئەوەی سوور نەبێت
          curl -LO https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz
          mkdir -p ~/theos/sdks
          tar -xf iPhoneOS14.5.sdk.tar.xz -C ~/theos/sdks
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Build Dylib
        run: |
          export THEOS=~/theos
          make FINALPACKAGE=1
          
      - name: Upload Dylib
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: M1Store_Dylib
          path: .theos/obj/debug/*.dylib
